### ISSUE TITLE
Pages related to the process of creating a collective need to be updated

### ISSUE THREAD

**Issue by contraexemplo** [opencollective/documentation-old#58]
Open Collective will release an updated version of the Create Collective form, including the GitHub flow. Pages that include information related to those flows need to be updated.

**Comment by contraexemplo** [comment]
### TODO
- [x] Complete all possible flows
- [x] Grab screenshots and GIFs
- [x] Update [Creating a Collective](https://docs.opencollective.com/help/collectives/create-collective)
- [ ] Update [OSC verification](https://docs.opencollective.com/help/collectives/osc-verification)

**Comment by znarf** [comment]
@contraexemplo sorry for the lack of synchronization, but the form is now live. Let's update the documentation when you can.

**Comment by contraexemplo** [comment]
@znarf That's alright. I'll be taking care exclusively of that today.

**Comment by contraexemplo** [comment]
Halfway there. Creating a Collective is done. Need to think of a way to update Open Source Collectives.
